//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Physics.Lang {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangEn() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Physics.Lang.LangEn", typeof(LangEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        internal static string backBt {
            get {
                return ResourceManager.GetString("backBt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change!.
        /// </summary>
        internal static string changeLang {
            get {
                return ResourceManager.GetString("changeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fundamental Concepts.
        /// </summary>
        internal static string concepts {
            get {
                return ResourceManager.GetString("concepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Most usable constants.
        /// </summary>
        internal static string constants {
            get {
                return ResourceManager.GetString("constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Final Time(s):.
        /// </summary>
        internal static string finalTime {
            get {
                return ResourceManager.GetString("finalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Final V(m/s):.
        /// </summary>
        internal static string finalV {
            get {
                return ResourceManager.GetString("finalV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to Concepts.
        /// </summary>
        internal static string goConcepts {
            get {
                return ResourceManager.GetString("goConcepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to constants.
        /// </summary>
        internal static string goConstants {
            get {
                return ResourceManager.GetString("goConstants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to equations.
        /// </summary>
        internal static string goEquations {
            get {
                return ResourceManager.GetString("goEquations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to Help.
        /// </summary>
        internal static string goHelp {
            get {
                return ResourceManager.GetString("goHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to problems.
        /// </summary>
        internal static string goProblems {
            get {
                return ResourceManager.GetString("goProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to videos.
        /// </summary>
        internal static string goVideoReviews {
            get {
                return ResourceManager.GetString("goVideoReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Initial Time(s):.
        /// </summary>
        internal static string initTime {
            get {
                return ResourceManager.GetString("initTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Initial V(m/s):.
        /// </summary>
        internal static string initV {
            get {
                return ResourceManager.GetString("initV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load changelog.
        /// </summary>
        internal static string loadChange {
            get {
                return ResourceManager.GetString("loadChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To main.
        /// </summary>
        internal static string mainScreenBt {
            get {
                return ResourceManager.GetString("mainScreenBt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actual.
        /// </summary>
        internal static string numVersion {
            get {
                return ResourceManager.GetString("numVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset all.
        /// </summary>
        internal static string resetBt {
            get {
                return ResourceManager.GetString("resetBt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Result:.
        /// </summary>
        internal static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Some problems to review.
        /// </summary>
        internal static string reviewProblems {
            get {
                return ResourceManager.GetString("reviewProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Historical.
        /// </summary>
        internal static string showHistorical {
            get {
                return ResourceManager.GetString("showHistorical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simple physics equations.
        /// </summary>
        internal static string simpleEq {
            get {
                return ResourceManager.GetString("simpleEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solve!.
        /// </summary>
        internal static string solveBt {
            get {
                return ResourceManager.GetString("solveBt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Physics review for students of highschool.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtain acceleration.
        /// </summary>
        internal static string toAc {
            get {
                return ResourceManager.GetString("toAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtain angular acceleration.
        /// </summary>
        internal static string toAngAc {
            get {
                return ResourceManager.GetString("toAngAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtain drop velocity.
        /// </summary>
        internal static string toFinalV {
            get {
                return ResourceManager.GetString("toFinalV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtain init V and max Height.
        /// </summary>
        internal static string toInitVH {
            get {
                return ResourceManager.GetString("toInitVH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtain kinetic energy.
        /// </summary>
        internal static string toKE {
            get {
                return ResourceManager.GetString("toKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current version.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video Reviews.
        /// </summary>
        internal static string VideoReviews {
            get {
                return ResourceManager.GetString("VideoReviews", resourceCulture);
            }
        }
    }
}
