//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Physics.Lang {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangEs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangEs() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Physics.Lang.LangEs", typeof(LangEs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formula de aceleracion.
        /// </summary>
        internal static string accelFormula {
            get {
                return ResourceManager.GetString("accelFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        internal static string ayuda {
            get {
                return ResourceManager.GetString("ayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        internal static string backBt {
            get {
                return ResourceManager.GetString("backBt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambia el lenguaje.
        /// </summary>
        internal static string CambiaLenguaje {
            get {
                return ResourceManager.GetString("CambiaLenguaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga registro de cambios.
        /// </summary>
        internal static string CargaRegistro {
            get {
                return ResourceManager.GetString("CargaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestion de conceptos.
        /// </summary>
        internal static string conceptos {
            get {
                return ResourceManager.GetString("conceptos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Constantes más usadas.
        /// </summary>
        internal static string ConstantesmasUsadas {
            get {
                return ResourceManager.GetString("ConstantesmasUsadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ecuaciones simples.
        /// </summary>
        internal static string ecuacionessimples {
            get {
                return ResourceManager.GetString("ecuacionessimples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar a un fichero.
        /// </summary>
        internal static string exportStrip {
            get {
                return ResourceManager.GetString("exportStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo.
        /// </summary>
        internal static string fileStrip {
            get {
                return ResourceManager.GetString("fileStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Velocidad angular final:.
        /// </summary>
        internal static string finalAngV {
            get {
                return ResourceManager.GetString("finalAngV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo final(s):.
        /// </summary>
        internal static string finalT {
            get {
                return ResourceManager.GetString("finalT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Velocidad final(s):.
        /// </summary>
        internal static string finalV {
            get {
                return ResourceManager.GetString("finalV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial:.
        /// </summary>
        internal static string historialLb {
            get {
                return ResourceManager.GetString("historialLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar historico.
        /// </summary>
        internal static string historicalStrip {
            get {
                return ResourceManager.GetString("historicalStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Velocidad angular inicial:.
        /// </summary>
        internal static string initAngV {
            get {
                return ResourceManager.GetString("initAngV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo inicial(s):.
        /// </summary>
        internal static string initT {
            get {
                return ResourceManager.GetString("initT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Velocidad inicial(s):.
        /// </summary>
        internal static string initV {
            get {
                return ResourceManager.GetString("initV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sacar Vo.
        /// </summary>
        internal static string initVHVmax {
            get {
                return ResourceManager.GetString("initVHVmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a ayuda.
        /// </summary>
        internal static string iraAyuda {
            get {
                return ResourceManager.GetString("iraAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a ventana conceptos.
        /// </summary>
        internal static string irAConceptos {
            get {
                return ResourceManager.GetString("irAConceptos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a ecuaciones.
        /// </summary>
        internal static string irAEcuaciones {
            get {
                return ResourceManager.GetString("irAEcuaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver videos.
        /// </summary>
        internal static string IraVideos {
            get {
                return ResourceManager.GetString("IraVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a ventana de constantes.
        /// </summary>
        internal static string irConstantes {
            get {
                return ResourceManager.GetString("irConstantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conocido su tiempo y sabiendo que al llegar al final su v es 0..
        /// </summary>
        internal static string lb1InitVHmax {
            get {
                return ResourceManager.GetString("lb1InitVHmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtenemos el valor de su V inicial.
        /// </summary>
        internal static string lb2InitVHmax {
            get {
                return ResourceManager.GetString("lb2InitVHmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cogemos su v0 calculado antes y el mismo tiempo.
        /// </summary>
        internal static string lb3InitVHmax {
            get {
                return ResourceManager.GetString("lb3InitVHmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asumimos que su posicion inicial es 0, está en el suelo..
        /// </summary>
        internal static string lb4InitVHmax {
            get {
                return ResourceManager.GetString("lb4InitVHmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usamos la formula de la ecuacion de posicion con aceleracion negativa..
        /// </summary>
        internal static string lb5InitHVmax {
            get {
                return ResourceManager.GetString("lb5InitHVmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usamos la ecuación de V final.
        /// </summary>
        internal static string lbEqInitHVmax {
            get {
                return ResourceManager.GetString("lbEqInitHVmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Muestra el historial.
        /// </summary>
        internal static string MuestraHistorial {
            get {
                return ResourceManager.GetString("MuestraHistorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version actual.
        /// </summary>
        internal static string numeroVersion {
            get {
                return ResourceManager.GetString("numeroVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver a inicio.
        /// </summary>
        internal static string principal {
            get {
                return ResourceManager.GetString("principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver problemas.
        /// </summary>
        internal static string problemasRepaso {
            get {
                return ResourceManager.GetString("problemasRepaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problemas para repasar.
        /// </summary>
        internal static string problemasRepasoLb {
            get {
                return ResourceManager.GetString("problemasRepasoLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar el historial completamente.
        /// </summary>
        internal static string resetBt {
            get {
                return ResourceManager.GetString("resetBt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultado:.
        /// </summary>
        internal static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resolver.
        /// </summary>
        internal static string solveBt {
            get {
                return ResourceManager.GetString("solveBt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sacar Hmax.
        /// </summary>
        internal static string SolveHmax {
            get {
                return ResourceManager.GetString("SolveHmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repaso de física para estudiantes.
        /// </summary>
        internal static string titulo {
            get {
                return ResourceManager.GetString("titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtener aceleracion.
        /// </summary>
        internal static string toAc {
            get {
                return ResourceManager.GetString("toAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtener aceleracion angular.
        /// </summary>
        internal static string toAngAc {
            get {
                return ResourceManager.GetString("toAngAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtener velocidad en caida.
        /// </summary>
        internal static string toFinalV {
            get {
                return ResourceManager.GetString("toFinalV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtener Vi y altura maxima.
        /// </summary>
        internal static string toInitVH {
            get {
                return ResourceManager.GetString("toInitVH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtener energia cinetica.
        /// </summary>
        internal static string toKE {
            get {
                return ResourceManager.GetString("toKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo total:.
        /// </summary>
        internal static string tTotal {
            get {
                return ResourceManager.GetString("tTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problemas para repasar.
        /// </summary>
        internal static string VersionActual {
            get {
                return ResourceManager.GetString("VersionActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Videos para aprender.
        /// </summary>
        internal static string videosRepaso {
            get {
                return ResourceManager.GetString("videosRepaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saca Vo.
        /// </summary>
        internal static string Vo {
            get {
                return ResourceManager.GetString("Vo", resourceCulture);
            }
        }
    }
}
